name: upload to s3
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
permissions:
  id-token: write  
  contents: write

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: take a copy of my src code
          uses: actions/checkout@v4
        - name: update README
          run: |
            echo "The s3 serverless hosting was updated at time: $(date -u)" > update.txt
            cat update.txt >> README.md
        - name: github access to README.md
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "automated update at $(date)" || echo "no new update"
            git push
        - name: Configure AWS credentials (OIDC)
          uses: aws-actions/configure-aws-credentials@v5
          with:
            role-to-assume: arn:aws:iam::862479276433:role/github-role
            aws-region: eu-north-1
        - name: deploying repo to s3 serverless hosting
          run: aws s3 cp ./ s3://my-webapp-aws-felix --recursive
